//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vreme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dataMetDatas
    {
        public int Id { get; set; }
        public string domain_title { get; set; }
        public string domain_shortTitle { get; set; }
        public string domain_longTitle { get; set; }
        public string domain_meteosiId { get; set; }
        public decimal domain_lat { get; set; }
        public decimal domain_lon { get; set; }
        public decimal domain_altitude { get; set; }
        public string dataSource_title { get; set; }
        public string sunrise { get; set; }
        public string sunset { get; set; }
        public string tsValid_issued { get; set; }
        public string tsValid_issued_day { get; set; }
        public string tsValid_issued_UTC { get; set; }
        public string tsValid_issued_RFC822 { get; set; }
        public string tsUpdated { get; set; }
        public string tsUpdated_day { get; set; }
        public string tsUpdated_UTC { get; set; }
        public string tsUpdated_RFC822 { get; set; }
        public string valid_day { get; set; }
        public string valid { get; set; }
        public string valid_UTC { get; set; }
        public string validStart { get; set; }
        public string validEnd { get; set; }
        public string nn_var_desc { get; set; }
        public string wwsyn_var_desc { get; set; }
        public string nn_iconwwsyn_icon { get; set; }
        public string wwsyn_icon { get; set; }
        public string t_var_desc { get; set; }
        public string t_var_unit { get; set; }
        public decimal t { get; set; }
        public byte t_state { get; set; }
        public string td_var_desc { get; set; }
        public string td_var_unit { get; set; }
        public decimal td { get; set; }
        public byte td_state { get; set; }
        public string tavg_var_desc { get; set; }
        public string tavg_var_unit { get; set; }
        public decimal tavg { get; set; }
        public byte tavg_state { get; set; }
        public string tx_var_desc { get; set; }
        public string tx_var_unit { get; set; }
        public decimal tx { get; set; }
        public byte tx_state { get; set; }
        public string tn_var_desc { get; set; }
        public string tn_var_unit { get; set; }
        public decimal tn { get; set; }
        public byte tn_state { get; set; }
        public string rh_var_desc { get; set; }
        public string rh_var_unit { get; set; }
        public byte rh { get; set; }
        public byte rh_state { get; set; }
        public string rhavg_var_desc { get; set; }
        public string rhavg_var_unit { get; set; }
        public byte rhavg { get; set; }
        public byte rhavg_state { get; set; }
        public string dd_var_desc { get; set; }
        public string dd_var_unit { get; set; }
        public string dd_shortText { get; set; }
        public string dd_icon { get; set; }
        public byte dd_state { get; set; }
        public string ddavg_var_desc { get; set; }
        public string ddavg_var_unit { get; set; }
        public string ddavg_shortText { get; set; }
        public string ddavg_longText { get; set; }
        public string ddavg_icon { get; set; }
        public byte ddavg_state { get; set; }
        public string ddmax_var_desc { get; set; }
        public string ddmax_var_unit { get; set; }
        public string ddmax_shortText { get; set; }
        public string ddmax_icon { get; set; }
        public byte ddmax_state { get; set; }
        public string ff_var_desc { get; set; }
        public string ff_var_unit { get; set; }
        public decimal ff_val { get; set; }
        public byte ff_val_kmh { get; set; }
        public byte ff_state { get; set; }
        public string ffavg_var_desc { get; set; }
        public string ffavg_var_unit { get; set; }
        public decimal ffavg_val { get; set; }
        public byte ffavg_val_kmh { get; set; }
        public byte ffavg_state { get; set; }
        public string ffmax_var_desc { get; set; }
        public string ffmax_var_unit { get; set; }
        public decimal ffmax_val { get; set; }
        public byte ffmax_val_kmh { get; set; }
        public byte ffmax_state { get; set; }
        public string msl_var_desc { get; set; }
        public string msl_var_unit { get; set; }
        public string mslavg_var_desc { get; set; }
        public string mslavg_var_unit { get; set; }
        public string p_var_desc { get; set; }
        public string p_var_unit { get; set; }
        public string pavg_var_desc { get; set; }
        public string pavg_var_unit { get; set; }
        public string rr_var_desc { get; set; }
        public string rr_var_unit { get; set; }
        public decimal rr_val { get; set; }
        public byte rr_state { get; set; }
        public string snow_var_desc { get; set; }
        public string snow_var_unit { get; set; }
        public string tp_12h_acc_var_desc { get; set; }
        public string tp_12h_acc_var_unit { get; set; }
        public decimal tp_12h_acc { get; set; }
        public byte tp_12h_acc_state { get; set; }
        public string tp_24h_acc_var_desc { get; set; }
        public string tp_24h_acc_var_unit { get; set; }
        public string tp_24h_acc { get; set; }
        public string tp_24h_acc_state { get; set; }
        public string tw_var_desc { get; set; }
        public string tw_var_unit { get; set; }
        public string gSunRad_var_desc { get; set; }
        public string gSunRad_var_unit { get; set; }
        public string gSunRadavg_var_desc { get; set; }
        public string gSunRadavg_var_unit { get; set; }
        public string diffSunRad_var_desc { get; set; }
        public string diffSunRad_var_unit { get; set; }
        public string diffSunRadavg_var_desc { get; set; }
        public string diffSunRadavg_var_unit { get; set; }
        public string vis_desc { get; set; }
        public string vis_unit { get; set; }
        public string t_5_cm_var_desc { get; set; }
        public string t_5_cm_var_unit { get; set; }
        public string tavg_5_cm_var_desc { get; set; }
        public string tavg_5_cm_var_unit { get; set; }
        public string tg_5_cm_var_desc { get; set; }
        public string tg_5_cm_var_unit { get; set; }
        public string tgavg_5_cm_var_desc { get; set; }
        public string tgavg_5_cm_var_unit { get; set; }
        public string tg_10_cm_var_desc { get; set; }
        public string tg_10_cm_var_unit { get; set; }
        public string tgavg_10_cm_var_desc { get; set; }
        public string tgavg_10_cm_var_unit { get; set; }
        public string tg_20_cm_var_desc { get; set; }
        public string tg_20_cm_var_unit { get; set; }
        public string tgavg_20_cm_var_desc { get; set; }
        public string tgavg_20_cm_var_unit { get; set; }
        public string tg_30_cm_var_desc { get; set; }
        public string tg_30_cm_var_unit { get; set; }
        public string tgavg_30_cm_var_desc { get; set; }
        public string tgavg_30_cm_var_unit { get; set; }
        public string tg_50_cm_var_desc { get; set; }
        public string tg_50_cm_var_unit { get; set; }
        public string tgavg_50_cm_var_desc { get; set; }
        public string tgavg_50_cm_var_unit { get; set; }
        public string hhs_var_desc { get; set; }
        public string hhs_var_unit { get; set; }
        public string ns_var_desc { get; set; }
        public string ns_var_unit { get; set; }
        public decimal rrHh { get; set; }
    }
}
